### ISSUE TITLE
Not able to take geolocation question type in OnlineSurvey if permission is not granted to the App.

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#15]
OPGSDK is not able to retrieve the location of device if permission for "LOCATION"  is not granted to the app. Also it is not requesting the permission at runtime.

**Comment by NeerajOPG** [comment]
added label

**Comment by NeerajOPG** [comment]
We have fixed this issue. 
As **navigator.geolocation** not showing permission dialog for location in android so we are using the custom cordova plugin to check the permission and requesting for it if not granted to app. we have updated the code in server.

**Comment by onepointpb** [comment]
This is working in staging app.
