### ISSUE TITLE
Few changes required inside the Lite version of demo app.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#18]
1. Audio upload is not working. It is throwing "file not found" error.
2. Correct the names PanelistPanel and UpdatePanelistProfile to PanellistPanel and UpdatePanellistProfile respectively.
3. Remove the contact access permission dialog from the demo app.
4. The camera interface is still opening in reverse mode for the tablet version of the app while using Barcode scan inside a survey.

**Comment by onepointpb** [comment]
1 and 3 fixed.
For 2 : the fields inside the methods are not changed.
![getpanellistpanel](https://user-images.githubusercontent.com/26476815/32591186-1cc9ce08-c544-11e7-8fe1-e42610a1dd28.png)

For 4 : the camera is now opening correctly, but after capturing the barcode it starts the survey again from begining.

**Comment by NeerajOPG** [comment]
It has been fixed.

**Comment by onepointpb** [comment]
Verified.
