### ISSUE TITLE
Audio Display question shows error in app

### ISSUE THREAD

**Issue by pavithra-opg** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#20]
We encountered an issue with the audio display question. When we click on play, it displays a message "Error".Please note this is happening only in IOS device but works fine in Android.

Issue was discussed with Chinthan and he informed me to ask UI team to add:

<audio width="400" controls="true"><source src="https://api.1pt.mobi/i/Media?mediaid=55638&amp;mediatype=mp3" type="audio/mp3" /> </audio>

Not audio tag src

@Chinthan , if I have missed any information, can you please add in.

Thanks & Regards
Pavithra R

**Comment by Chinthan** [comment]
<audio width="400" controls="true"><source src="URL" type="audio/mp3" /> </audio>

Add src tag in source node, not in audio node.

**Comment by pavithra-opg** [comment]
Issue raised in appropriate channel,hence closing this issue.
