### ISSUE TITLE
When using forgotPassword from opgsdk_lite_v1.5 the link from the email redirects to OPG website, to login 

### ISSUE THREAD

**Issue by andramarin** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#26]
This behaviour is recent. Before, the user was redirected to a screen where he should add the new and old password. Can you make a change and redirect user to this screen. The login screen is not relevant for the user, since the OPG is used in background in the app.

**Comment by NeerajOPG** [comment]
Hi @andramarin 
Thanks for reporting the issue. This is known issue for us and we are working on it.
we will fix it as soon as possible.
Issue : https://github.com/OnePointGlobal/OnePoint-Global-Account-Toolkit/issues/378

**Comment by NeerajOPG** [comment]
Hi @andramarin 
The issue is fixed. 
If it  will not work then please clear the browser cookies. 

Please let us know if you need anything else.
Thanks

**Comment by andramarin** [comment]
We tested this change, and after clearing cache the loded page has changed. 
But the password does not change, and we cannot login with the new one.

**Comment by andramarin** [comment]
@NeerajOPG do you have any updates on this?

**Comment by NeerajOPG** [comment]
@andramarin My sincere apologies for the delayed response. 
we are working on it and will resolve it soon. 
We will update once it is fixed.

**Comment by andramarin** [comment]
That is great, thank you

**Comment by NeerajOPG** [comment]
@andramarin
The issue has fixed and released.
Please test and confirm.

**Comment by NeerajOPG** [comment]
It is working now so we are closing it.
