### ISSUE TITLE
After creating a user through OPG API, when logging in with credentials from email, we reveive this error 

### ISSUE THREAD

**Issue by andramarin** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#27]
'These credentials are not used by this user.'

**Comment by andramarin** [comment]
we use method addPannellist

**Comment by andramarin** [comment]
By creating another account, when I loggin through the opgsdk_lite_v1.5 i get this error "Unauthorized access - Try with Basic Authentication"

**Comment by NeerajOPG** [comment]
Thanks @andramarin,
Here are the possible reason for this error
**By creating another account, when I loggin through the opgsdk_lite_v1.5 i get this error "Unauthorized access - Try with Basic Authentication"**

May be you are not passing the correct ADMIN_USERNAME and ADMIN_SHAREDKEY in initialize() method. Pass the ADMIN_USERNAME  and ADMIN_SHAREDKEY  of account in which you have added panellist using addPanellist method.

please refer the  documentation
[How to get surveys using panellist authentication?](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/wiki/03.-How-to-get-surveys-using-panellist-authentication%3F)

**Comment by andramarin** [comment]
With users that already exist in the pannellist previously, i have no problems logging in. This issue appears for new users. Do you still think that the ADMIN_USERNAME and ADMIN_SAREDKEY is the problem?

**Comment by NeerajOPG** [comment]
@andramarin 
we are not able to reproduce  the issue which you are getting.
Can you provide some steps to produce it ?

**This issue appears for new users.**  You mean to say for new panellist.

I have tested it by adding new panellist to an existing OnePoint ToolKit account and it is working fine.
Check the [DemoSurveys ](https://github.com/OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android/tree/master/DemoSurveysAndroid)app

**Comment by andramarin** [comment]
I solved the following error " Try with Basic Authentication". It was due to a mix of production and staging ADMIN_SHAREDKEY. 

I still get this error for newly users added to the pannellist. 'These credentials are not used by this user.'

**Comment by andramarin** [comment]
We've done some research ourselves and there was a mixup between 2 accounts (staging and production). This error appears when you are added into the pannellist of one account, and want to login into the other account. 
Unfortunately it is an error hard to understand and figure out why it happens from this message, since it does not say that you don't belong to that account/pannellist.

**Comment by NeerajOPG** [comment]
@andramarin It is great that you found the root cause. going forward we will make error message more understandable.

**Comment by andramarin** [comment]
Great, it sounds good. Thank you for helping us investigate this.
