### ISSUE TITLE
URL present in password reset email triggered through SDK app is throwing error when we browse it

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#3]
URL present in password reset email triggered through SDK app is throwing error
when we browse it.

**Comment by dinesh-opg** [comment]
This cannot handled in the opgsdk. It needs to be handled from server side.

**Comment by onepointpb** [comment]
Reset password URL is not throwing error while browsing.
