### ISSUE TITLE
Few themes are getting displayed in response but theme set in test panel (Panel ID 3921) is not reflecting in response.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#5]
Few themes are getting displayed in response but theme set in test panel (Panel ID 3921) is not reflecting in response.

**Comment by NeerajOPG** [comment]
This issue has been fixed. Actually we are getting the response but not showing that field in UI. I have updated the DemoApp.
