### ISSUE TITLE
In OPGSDKv1.7_lite, for Video upload question we are not able to upload video that is having length more than 1 sec. 

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#7]
It displayed the error: "Video upload failed : An error occurred. Please try again, else contact support."

**Comment by dinesh-opg** [comment]
The above is working fine in the dev version.We are able to upload the video.May be we need to do some configuration settings on the server side.Please check with dotnet team.

**Comment by vivek-onepoint** [comment]
We have fixed the issue and its working fine in Live (tested in postman). You can check once by uploading a video.

**Comment by nikul-opg** [comment]
issue is fixed and tested. Working fine.
