### ISSUE TITLE
Images for Read Me file

### ISSUE THREAD

**Issue by hitesh-opg** [OnePointGlobal/OnePoint-Global-Mobile-App-SDK-Android#8]
![panellistcredentials](https://user-images.githubusercontent.com/26539946/30054776-d82ef402-924a-11e7-9142-8c14bb5ecf50.png)

![profile](https://user-images.githubusercontent.com/26476815/30065535-d4df4f0e-9272-11e7-9626-f375a13413ad.png)

![sharedkey](https://user-images.githubusercontent.com/26476815/30065540-da2c81c0-9272-11e7-86f6-c73af19ac3fe.png)

**Comment by hitesh-opg** [comment]
![adminusername](https://user-images.githubusercontent.com/26539946/30054878-3611be74-924b-11e7-81f6-5ab25a018128.png)

**Comment by hitesh-opg** [comment]
![adminmenu](https://user-images.githubusercontent.com/26539946/30054944-76d522ca-924b-11e7-898d-44642193667f.PNG)

**Comment by dinesh-opg** [comment]
![android_custom_control_screen_1](https://user-images.githubusercontent.com/26459785/33654453-2cd4f3b0-da96-11e7-95dd-f231b0255180.png)

**Comment by dinesh-opg** [comment]
![android_custom_control_screen_2](https://user-images.githubusercontent.com/26459785/33654462-3aa9b16a-da96-11e7-8e4b-3d3a27342750.png)

**Comment by dinesh-opg** [comment]
![android_custom_control_screen_3](https://user-images.githubusercontent.com/26459785/33654472-45938402-da96-11e7-8107-5bc5e11e5a0f.png)

**Comment by NeerajOPG** [comment]
it is not issue.
